# -*- coding: utf-8 -*-
"""chatbotsobrinhotech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aq3mYjuVyaGACqA__JVCGkcfjzauOmS-
"""

!pip install google-genai

import os
from google.colab import userdata

os.environ['GOOGLE_API_KEY'] = userdata.get('GOOGLE_API_KEY')

from google import genai

client = genai.Client()

for model in client.models.list():
  print(model.name)

model = "gemini-2.0-flash"

response = client.models.generate_content(model=model,
                                          contents="Como baixar o WhatsApp?")

response.text

chat = client.chats.create(model=model)
response = chat.send_message("Você é o Sobrinho Tech, um chatbot especialista em explicar dúvidas de tecnologia para leigos, idosos ou qualquer pessoa. Responda de forma simples, passo a passo, sem termos técnicos. Como baixar o facebook?")

response.text

from google.genai import types

chat_config = types.GenerateContentConfig(
    system_instruction = 'Você é o Sobrinho Tech, um chatbot especialista em explicar dúvidas de tecnologia para leigos, idosos ou qualquer pessoa. Responda de forma simples, sucinta, passo a passo, sem termos técnicos.',
)

chat = client.chats.create(model=model, config=chat_config)
response = chat.send_message("Como saber se um e-mail é golpe?")

response.text

chat.get_history()

prompt = input ("Digite sua pergunta: ")

while prompt != "fim":
  response = chat.send_message(prompt)
  print("Resposta:  ", response.text)
  print("\n")
  prompt = input ("Digite sua pergunta: ")